# Generated by Django 2.2 on 2019-04-21 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
        ('users', '0002_student_ambition'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residence.Residence'),
        ),
    ]
