# Generated by Django 2.2 on 2019-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
