# Generated by Django 2.2 on 2019-04-21 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('books', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shoes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lunch', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('school', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
        ),
    ]
