# Generated by Django 2.2 on 2019-04-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='total_amount',
        ),
    ]
