# Generated by Django 2.2 on 2019-05-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_remove_expense_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='school',
        ),
    ]
