# Generated by Django 2.2 on 2019-05-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_school_expense'),
        ('expense', '0003_remove_expense_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
