# Generated by Django 2.2 on 2019-04-21 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0001_initial'),
        ('users', '0002_student_ambition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('donation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('expense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.Expense')),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Relation')),
            ],
        ),
    ]
