# Generated by Django 2.2 on 2019-04-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='active',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
