# Generated by Django 2.2 on 2019-05-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('sponsorship', '0002_auto_20190422_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='expense',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
