# Generated by Django 2.2 on 2019-05-01 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expense_school'),
        ('sponsorship', '0003_auto_20190501_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='school',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.Expense'),
        ),
    ]
