# Generated by Django 2.2 on 2019-05-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_remove_expense_school'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='expense',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.Expense'),
        ),
    ]
