# Generated by Django 2.2 on 2019-05-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='expense',
        ),
    ]
